# Generated by Django 5.0.2 on 2024-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_visitcategory_alter_cvisit_visitreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvisit',
            name='loadHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvisit',
            name='workingHours',
            field=models.IntegerField(default=0),
        ),
    ]
