# Generated by Django 5.0.4 on 2024-04-20 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_clist_ctechnician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clist',
            name='cTechnician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
