# Generated by Django 5.0.4 on 2024-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_clist_ctechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvisit',
            name='cNotes',
            field=models.TextField(default=''),
        ),
    ]
