# Generated by Django 5.0.2 on 2024-04-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_cvisit_cnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clist',
            name='cTechnician',
        ),
        migrations.AddField(
            model_name='cvisit',
            name='cTechnician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
