# Generated by Django 5.0.2 on 2024-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_remove_clist_ctechnician_cvisit_ctechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='clist',
            name='salesman',
            field=models.CharField(default='', max_length=32),
        ),
    ]
