# Generated by Django 5.0.2 on 2024-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_clist_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clist',
            name='salesman',
            field=models.CharField(max_length=32),
        ),
    ]
